Integrate migrations into config and model (+squashed)
Squashed:
Drop config.database_create_tables (not used):
- pick 058f09a7ec Integrate migrations design into config and model code
- squash 557fac122e Drop config.database_create_tables (not used)

Squashed:
Handle error when revision not found; add test case:
- pick 36cdf4bfc5 Integrate migrations design into config and model code (+squashed)
- squash 64e8635fa4 Handle error when revision not found; add test case

Squashed:
Avoid extra trip to db via lazy load of alembic version heads
- pick 45028e6f57 Integrate migrations design into config and model code (+squashed)
- squash 649f8d17d5 Avoid extra trip to db via lazy load of alembic version heads

Squashed:
Use correct db options for both engines; resolve todos
- pick c9048da963 Integrate migrations into config and model (+squashed)
- squash 6064327fc7 Use correct db options for both engines; resolve todos

Squashed:
Squashed: log messages, tests, db scripts, mypy
- pick 439876bb17 Integrate migrations into config and model (+squashed)
- squash 83855c8119 Squashed: log messages, tests, db scripts, mypy

Squashed:
Add informative log/error messages; add tests for new methods
Setup infrastructure for running db scripts:
- pick 403197aad9 Add informative log/error messages; add tests for new methods
- squash 501d5e10f8 Setup infrastructure for running db scripts

Squashed:
Move is-one-db check into model.database_utils
- pick 406a952d7d Add informative log/error messages; add tests for new methods (+squashed)
- squash c977669847 Move is-one-db check into model.database_utils

Squashed:
Address existing mypy error (see note)
- pick 878465d5d6 Squashed: log messages, tests, db scripts
- squash e998a04d87 Address existing mypy error (see note)

This is a (possible) bug that has existed on dev. To expose it, simply
change this call to init_models_from_config
(https://github.com/galaxyproject/galaxy/blob/release_21.09/lib/galaxy/config/__init__.py#L1302)
to a call directly to mapping.init(). The result will be 6 mypy errors.

The reason is that the mapping.init() function
(https://github.com/galaxyproject/galaxy/blob/release_21.09/lib/galaxy/model/mapping.py#L79)
specifies its return type as GalaxyModelMapping - which results in
several errors of this type:

lib/galaxy/app.py:178: error: Definition of "model" in base class "MinimalApp" is incompatible with definition in base class "ConfiguresGalaxyMixin"

When we call an intermediary function (that does not have a return type
specified), mypy is happy.

This should be addressed in a separate issue/PR. Removing the return
type is the simplest (temporary) solution.